### ISSUE TITLE
perl stripping filter

### ISSUE THREAD

**Issue by glensc** [shoichikaji/App-FatPacker-Simple#5]
hi

i would like to perl strip only selected modules (files). in fact i want  to strip all external modules, except files from my own package. (strip: `local`, no-strip: `lib`)

the reason i don't want to strip my own modules is that it makes very hard to debug problems by me or end users if the code is minified to single line.

**Comment by glensc** [comment]
for now, i minify myself and call `fatpack-simple` with `--no-perl-strip` option to achieve the same goal

```
    find local/lib -name '*.pm' | xargs perlstrip -s
```

**Comment by skaji** [comment]
I myself sometimes want such feature :-)
But I don't know what interface is good to specify not-perl-stripped files or directory,
and I want to keep App::FatPacker::Simple simple, eg, no complicated options.
- Yes, you can use `find` or something before fatpack-simple :)
- You can propose simple interface to specify not-perl-stripped files or directory.
- Check other module, such as https://metacpan.org/release/App-depak

**Comment by glensc** [comment]
i was thinking maybe just `--exclude-strip=REGEX` parameter, which could be added to [find](https://github.com/shoichikaji/App-FatPacker-Simple/blob/0.04/lib/App/FatPacker/Simple.pm#L167-L189) call

**Comment by skaji** [comment]
@glensc Sorry I'm late, but could you check #7 ?

**Comment by glensc** [comment]
no hurry, because i already have solution:
https://github.com/skaji/App-FatPacker-Simple/issues/5#issuecomment-143414400
