### ISSUE TITLE
AnyEvent and pl files

### ISSUE THREAD

**Issue by ccakes** [shoichikaji/App-FatPacker-Simple#8]
AnyEvent (possibly others, but this is all I've found) include *.pl files in the distribution which are required to run. 

Adding `pl` to the match on [this line](https://github.com/skaji/App-FatPacker-Simple/blob/b14d64d3c57129fd28e378f4faac94433c2628dd/lib/App/FatPacker/Simple.pm#L189) makes it all work but I'm not sure what the wider implications might be. I'm assuming some cruft from other distributions would get packed as well but I'm not sure what a better workaround might be.

Would you be open to this or is there a better way to handle AE that I might be missing?

**Comment by skaji** [comment]
@ccakes thanks, released https://metacpan.org/release/SKAJI/App-FatPacker-Simple-0.08
